[package]
name = "eagle"
version = "0.1.0"
authors = ["Adam Goforth <code@adamgoforth.com>"]
license = "MIT"

[dependencies]
docopt = "1.0"
notify = "^2.4.1"
libc = "^0.2.8"
rand = "^0.3.11"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

